# Automatically generated by configure - do not modify

all:
SRC_PATH=/o/repos.hobby/pc110-web/.cache/pc110-wasm-src-pointerfix
TARGET_DIRS=i386-softmmu
GDB=
SUBDIRS=
PYTHON=O:/repos.hobby/pc110-web/.cache/pc110-wasm-build-pointerfix2/pyvenv/Scripts/python.exe -B
MKVENV_ENSUREGROUP=O:/repos.hobby/pc110-web/.cache/pc110-wasm-build-pointerfix2/pyvenv/Scripts/python.exe -B /o/repos.hobby/pc110-web/.cache/pc110-wasm-src-pointerfix/python/scripts/mkvenv.py ensuregroup 
GENISOIMAGE=
MESON=O:/repos.hobby/pc110-web/.cache/pc110-wasm-build-pointerfix2/pyvenv/bin/meson
NINJA=O:/repos.hobby/pc110-web/.cache/wasm-deps-pointerfix/tools/ninja.exe
EXESUF=
TCG_TESTS_WITH_COMPILERS=
