# Automatically generated by configure - do not modify

all:
SRC_PATH=/o/repos.hobby/pc110-web/.cache/pc110-wasm-src-wasm32
TARGET_DIRS=i386-softmmu
GDB=
SUBDIRS=
PYTHON=O:/repos.hobby/pc110-web/.cache/pc110-wasm-build-wasm32/pyvenv/Scripts/python.exe -B
MKVENV_ENSUREGROUP=O:/repos.hobby/pc110-web/.cache/pc110-wasm-build-wasm32/pyvenv/Scripts/python.exe -B /o/repos.hobby/pc110-web/.cache/pc110-wasm-src-wasm32/python/scripts/mkvenv.py ensuregroup 
GENISOIMAGE=
MESON=O:/repos.hobby/pc110-web/.cache/pc110-wasm-build-wasm32/pyvenv/bin/meson
NINJA=O:/repos.hobby/pc110-web/.cache/wasm32-direct-pass1/deps/tools/ninja.exe
EXESUF=
TCG_TESTS_WITH_COMPILERS=
